// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PC.Context;

#nullable disable

namespace PC.Context.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231225072307_create-tblPsychologistAboutUs")]
    partial class createtblPsychologistAboutUs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PD.Entity.DiscountAndOrder.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiscountWithMoney")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountWithPercentage")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PatientId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("PsychologistId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PsychologistId");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("PD.Entity.DiscountAndOrder.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscountAmount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientTurnId")
                        .HasColumnType("int");

                    b.Property<int?>("PayAmount")
                        .HasColumnType("int");

                    b.Property<int?>("PsychologistId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("RefId")
                        .HasColumnType("int");

                    b.Property<int?>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientTurnId");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("TestId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("PD.Entity.Patient.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ObjPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaitentId")
                        .HasColumnType("int");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaitentId");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PD.Entity.Patient.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPatient")
                        .HasColumnType("bit");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientExam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("TestId");

                    b.ToTable("PatientExams");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientFiles");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientResponses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PathFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientExamId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientExamId");

                    b.ToTable("PatientResponsesExamies");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientTurn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConsultationDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCanseled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisited")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("PsychologistWorkingDateAndTimeId")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfConsultationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PsychologistWorkingDateAndTimeId");

                    b.HasIndex("TypeOfConsultationId");

                    b.ToTable("PatientTurn");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PsychologistId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.Psychologist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("Commission")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvidencePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MedicalLicennseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Psychologists");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistAboutUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<string>("TextAbout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PsychologistId");

                    b.ToTable("PsychologistAboutUs");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistTypeOfConsultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfConsultationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("TypeOfConsultationId");

                    b.ToTable("PsychologistTypeOfConsultations");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistWorkingDateAndTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<int>("PsychologistWorkingDaysId")
                        .HasColumnType("int");

                    b.Property<int>("PsychologistWorkingHoursId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("PsychologistWorkingDaysId");

                    b.HasIndex("PsychologistWorkingHoursId");

                    b.ToTable("PsychologistWorkingDateAndTime");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistWorkingDays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PsychologistWorkingDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(7186),
                            Day = "شنبه",
                            DayEn = "Saturday",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(7192),
                            Day = "یک‌شنبه",
                            DayEn = "Sunday",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(7193),
                            Day = "دو‌شنبه",
                            DayEn = "Monday",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(7194),
                            Day = "سه‌شنبه",
                            DayEn = "Tuesday",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(7195),
                            Day = "چهارشنبه",
                            DayEn = "Wednesday",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(7197),
                            Day = "پنج‌شنبه",
                            DayEn = "Thursday",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(7197),
                            Day = "جمعه",
                            DayEn = "Friday",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistWorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PsychologistWorkingHours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6790)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 12, 25, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6794)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 12, 25, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6798)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 12, 25, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6800)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 12, 25, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6803)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 12, 25, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6817)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 12, 25, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6820)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 12, 25, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6823)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 12, 25, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6826)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 12, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6829)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 12, 25, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6832)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 12, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6835)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 12, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6838)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 12, 25, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6897)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 12, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6900)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 12, 25, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6902)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 12, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6905)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 12, 25, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6909)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 12, 25, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6911)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 12, 25, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6914)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 12, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6917)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 12, 25, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6919)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 12, 25, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6922)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 12, 25, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6924)
                        });
                });

            modelBuilder.Entity("PD.Entity.Psychologist.TypeOfConsultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TypeOfConsultation");
                });

            modelBuilder.Entity("PD.Entity.Role.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 12, 25, 10, 53, 7, 140, DateTimeKind.Local).AddTicks(4179),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "AdminManagment"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 12, 25, 10, 53, 7, 140, DateTimeKind.Local).AddTicks(4186),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 12, 25, 10, 53, 7, 140, DateTimeKind.Local).AddTicks(4187),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Patient"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 12, 25, 10, 53, 7, 140, DateTimeKind.Local).AddTicks(4189),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Psychologist"
                        });
                });

            modelBuilder.Entity("PD.Entity.Test.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("PD.Entity.Test.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("PD.Entity.Test.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("PD.Entity.User.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 12, 25, 10, 53, 7, 140, DateTimeKind.Local).AddTicks(4225),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "آقا"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 12, 25, 10, 53, 7, 140, DateTimeKind.Local).AddTicks(4228),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "خانم"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 12, 25, 10, 53, 7, 140, DateTimeKind.Local).AddTicks(4229),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "دیگر"
                        });
                });

            modelBuilder.Entity("PD.Entity.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MobailActiveStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivationCode = "7124626f-30d5-47d1-bcdc-6ea36177ecea",
                            CreatedAt = new DateTime(2023, 12, 25, 10, 53, 7, 142, DateTimeKind.Local).AddTicks(6525),
                            FName = "مدیر",
                            GenderId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            LName = "سیستم",
                            MobailActiveStatus = true,
                            Password = "AQAAAAEAACcQAAAAEKAusIjJ2SfSH4QOulby4WfRX0Xhf1D66O28v9Uw2xNEu9c0cNK/JQId4pj7sxPbCA==",
                            Phone = "Administrator@1402",
                            RoleID = 1
                        });
                });

            modelBuilder.Entity("PD.Entity.DiscountAndOrder.Discount", b =>
                {
                    b.HasOne("PD.Entity.Patient.Patient", "Patient")
                        .WithMany("Discount")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Psychologist.Psychologist", "Psychologist")
                        .WithMany("Discount")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("PD.Entity.DiscountAndOrder.Order", b =>
                {
                    b.HasOne("PD.Entity.Patient.Patient", "Patient")
                        .WithMany("Orders")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Patient.PatientTurn", "PatientTurn")
                        .WithMany("Order")
                        .HasForeignKey("PatientTurnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PD.Entity.Psychologist.Psychologist", "Psychologist")
                        .WithMany("Order")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Test.Test", "Test")
                        .WithMany("Orders")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Patient");

                    b.Navigation("PatientTurn");

                    b.Navigation("Psychologist");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("PD.Entity.Patient.Comment", b =>
                {
                    b.HasOne("PD.Entity.Patient.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PaitentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PD.Entity.Psychologist.Psychologist", "Psychologist")
                        .WithMany()
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.User.User", "AdUser")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AdUser");

                    b.Navigation("Patient");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("PD.Entity.Patient.Patient", b =>
                {
                    b.HasOne("PD.Entity.User.User", "User")
                        .WithMany("Patient")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientExam", b =>
                {
                    b.HasOne("PD.Entity.Patient.Patient", "Patient")
                        .WithMany("PatientExam")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Test.Test", "Test")
                        .WithMany("PatientExam")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientFile", b =>
                {
                    b.HasOne("PD.Entity.Patient.Patient", "Patient")
                        .WithMany("PatientFile")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientResponses", b =>
                {
                    b.HasOne("PD.Entity.Patient.PatientExam", "PatientExam")
                        .WithMany("PatientResponses")
                        .HasForeignKey("PatientExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PatientExam");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientTurn", b =>
                {
                    b.HasOne("PD.Entity.Patient.Patient", "Patient")
                        .WithMany("PatientTurns")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Psychologist.PsychologistWorkingDateAndTime", "PsychologistWorkingDateAndTime")
                        .WithMany("PatientTurns")
                        .HasForeignKey("PsychologistWorkingDateAndTimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Psychologist.TypeOfConsultation", "TypeOfConsultation")
                        .WithMany("PatientTurns")
                        .HasForeignKey("TypeOfConsultationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("PsychologistWorkingDateAndTime");

                    b.Navigation("TypeOfConsultation");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.Article", b =>
                {
                    b.HasOne("PD.Entity.Psychologist.Psychologist", "Psychologist")
                        .WithMany("Articles")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.Psychologist", b =>
                {
                    b.HasOne("PD.Entity.User.User", "User")
                        .WithMany("Psychologists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistAboutUs", b =>
                {
                    b.HasOne("PD.Entity.Psychologist.Psychologist", "Psychologist")
                        .WithMany("AboutUsList")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistTypeOfConsultation", b =>
                {
                    b.HasOne("PD.Entity.Psychologist.Psychologist", "Psychologist")
                        .WithMany("PsychologistTypeOfConsultations")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Psychologist.TypeOfConsultation", "TypeOfConsultation")
                        .WithMany("PsychologistTypeOfConsultations")
                        .HasForeignKey("TypeOfConsultationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Psychologist");

                    b.Navigation("TypeOfConsultation");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistWorkingDateAndTime", b =>
                {
                    b.HasOne("PD.Entity.Psychologist.Psychologist", "Psychologist")
                        .WithMany("PsychologistWorkingDateAndTime")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Psychologist.PsychologistWorkingDays", "PsychologistWorkingDays")
                        .WithMany("PsychologistWorkingDateAndTimes")
                        .HasForeignKey("PsychologistWorkingDaysId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Psychologist.PsychologistWorkingHours", "PsychologistWorkingHours")
                        .WithMany("PsychologistWorkingDateAndTimes")
                        .HasForeignKey("PsychologistWorkingHoursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Psychologist");

                    b.Navigation("PsychologistWorkingDays");

                    b.Navigation("PsychologistWorkingHours");
                });

            modelBuilder.Entity("PD.Entity.Test.Answer", b =>
                {
                    b.HasOne("PD.Entity.Test.Question", "Question")
                        .WithMany("Answer")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PD.Entity.Test.Question", b =>
                {
                    b.HasOne("PD.Entity.Test.Test", "Test")
                        .WithMany("Question")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("PD.Entity.User.User", b =>
                {
                    b.HasOne("PD.Entity.User.Gender", "Gender")
                        .WithMany("Users")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Role.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PD.Entity.Patient.Patient", b =>
                {
                    b.Navigation("Discount");

                    b.Navigation("Orders");

                    b.Navigation("PatientExam");

                    b.Navigation("PatientFile");

                    b.Navigation("PatientTurns");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientExam", b =>
                {
                    b.Navigation("PatientResponses");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientTurn", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.Psychologist", b =>
                {
                    b.Navigation("AboutUsList");

                    b.Navigation("Articles");

                    b.Navigation("Discount");

                    b.Navigation("Order");

                    b.Navigation("PsychologistTypeOfConsultations");

                    b.Navigation("PsychologistWorkingDateAndTime");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistWorkingDateAndTime", b =>
                {
                    b.Navigation("PatientTurns");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistWorkingDays", b =>
                {
                    b.Navigation("PsychologistWorkingDateAndTimes");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistWorkingHours", b =>
                {
                    b.Navigation("PsychologistWorkingDateAndTimes");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.TypeOfConsultation", b =>
                {
                    b.Navigation("PatientTurns");

                    b.Navigation("PsychologistTypeOfConsultations");
                });

            modelBuilder.Entity("PD.Entity.Role.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PD.Entity.Test.Question", b =>
                {
                    b.Navigation("Answer");
                });

            modelBuilder.Entity("PD.Entity.Test.Test", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("PatientExam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PD.Entity.User.Gender", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PD.Entity.User.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Patient");

                    b.Navigation("Psychologists");
                });
#pragma warning restore 612, 618
        }
    }
}
