// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PC.Context;

#nullable disable

namespace PC.Context.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231213091855_init-database")]
    partial class initdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PD.Entity.DiscountAndOrder.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiscountWithMoney")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountWithPercentage")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PatientId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("PsychologistId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PsychologistId");

                    b.ToTable("Discount");
                });

            modelBuilder.Entity("PD.Entity.DiscountAndOrder.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscountAmount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientTurnId")
                        .HasColumnType("int");

                    b.Property<int?>("PayAmount")
                        .HasColumnType("int");

                    b.Property<int?>("PsychologistId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("RefId")
                        .HasColumnType("int");

                    b.Property<int?>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientTurnId");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("TestId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("PD.Entity.Patient.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FirstUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LastUserId")
                        .HasColumnType("int");

                    b.Property<string>("ObjPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FirstUserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PD.Entity.Patient.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientExam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("TestId");

                    b.ToTable("PatientExams");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientFiles");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientResponses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PathFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientExamId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientExamId");

                    b.ToTable("PatientResponsesExamies");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientTurn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConsultationDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCanseled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisited")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("PsychologistWorkingDateAndTimeId")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfConsultationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PsychologistWorkingDateAndTimeId");

                    b.HasIndex("TypeOfConsultationId");

                    b.ToTable("PatientTurn");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.Psychologist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("Commission")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvidencePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MedicalLicennseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Psychologists");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistTypeOfConsultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfConsultationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("TypeOfConsultationId");

                    b.ToTable("PsychologistTypeOfConsultations");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistWorkingDateAndTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PsychologistId")
                        .HasColumnType("int");

                    b.Property<int>("PsychologistWorkingDaysId")
                        .HasColumnType("int");

                    b.Property<int>("PsychologistWorkingHoursId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PsychologistId");

                    b.HasIndex("PsychologistWorkingDaysId");

                    b.HasIndex("PsychologistWorkingHoursId");

                    b.ToTable("PsychologistWorkingDateAndTime");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistWorkingDays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PsychologistWorkingDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(5614),
                            Day = "شنبه",
                            DayEn = "Saturday",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(5622),
                            Day = "یک‌شنبه",
                            DayEn = "Sunday",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(5623),
                            Day = "دو‌شنبه",
                            DayEn = "Monday",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(5624),
                            Day = "سه‌شنبه",
                            DayEn = "Tuesday",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(5625),
                            Day = "چهارشنبه",
                            DayEn = "Wednesday",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(5626),
                            Day = "پنج‌شنبه",
                            DayEn = "Thursday",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(5627),
                            Day = "جمعه",
                            DayEn = "Friday",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistWorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PsychologistWorkingHours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4929)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 12, 13, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4935)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 12, 13, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4938)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 12, 13, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4945)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 12, 13, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4948)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 12, 13, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4959)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 12, 13, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4961)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 12, 13, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4964)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 12, 13, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4966)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 12, 13, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4970)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 12, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4973)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 12, 13, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4975)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 12, 13, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4978)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 12, 13, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4981)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 12, 13, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4983)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 12, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4986)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 12, 13, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4988)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 12, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4993)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 12, 13, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4995)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 12, 13, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4998)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 12, 13, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(5000)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 12, 13, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(5003)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 12, 13, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(5006)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 12, 13, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(5008)
                        });
                });

            modelBuilder.Entity("PD.Entity.Psychologist.TypeOfConsultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TypeOfConsultation");
                });

            modelBuilder.Entity("PD.Entity.Role.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 12, 13, 12, 48, 55, 398, DateTimeKind.Local).AddTicks(3554),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "AdminManagment"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 12, 13, 12, 48, 55, 398, DateTimeKind.Local).AddTicks(3566),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 12, 13, 12, 48, 55, 398, DateTimeKind.Local).AddTicks(3567),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Patient"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 12, 13, 12, 48, 55, 398, DateTimeKind.Local).AddTicks(3568),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Psychologist"
                        });
                });

            modelBuilder.Entity("PD.Entity.Test.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("PD.Entity.Test.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("PD.Entity.Test.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("PD.Entity.User.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 12, 13, 12, 48, 55, 398, DateTimeKind.Local).AddTicks(3613),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "آقا"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 12, 13, 12, 48, 55, 398, DateTimeKind.Local).AddTicks(3617),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "خانم"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 12, 13, 12, 48, 55, 398, DateTimeKind.Local).AddTicks(3619),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "دیگر"
                        });
                });

            modelBuilder.Entity("PD.Entity.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MobailActiveStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivationCode = "c8e62252-e614-4052-908d-6871af651f32",
                            CreatedAt = new DateTime(2023, 12, 13, 12, 48, 55, 400, DateTimeKind.Local).AddTicks(4725),
                            FName = "مدیر",
                            GenderId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            LName = "سیستم",
                            MobailActiveStatus = true,
                            Password = "AQAAAAEAACcQAAAAENu9skvcG/JH7+9Rx81yiYNkFZ9n71vkiGhsyfovVldqL6+vFiLUiKO/NZtQbnnTNA==",
                            Phone = "Administrator@1402",
                            RoleID = 1
                        });
                });

            modelBuilder.Entity("PD.Entity.DiscountAndOrder.Discount", b =>
                {
                    b.HasOne("PD.Entity.Patient.Patient", "Patient")
                        .WithMany("Discount")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Psychologist.Psychologist", "Psychologist")
                        .WithMany("Discount")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Psychologist");
                });

            modelBuilder.Entity("PD.Entity.DiscountAndOrder.Order", b =>
                {
                    b.HasOne("PD.Entity.Patient.Patient", "Patient")
                        .WithMany("Orders")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Patient.PatientTurn", "PatientTurn")
                        .WithMany("Order")
                        .HasForeignKey("PatientTurnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PD.Entity.Psychologist.Psychologist", "Psychologist")
                        .WithMany("Order")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Test.Test", "Test")
                        .WithMany("Orders")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Patient");

                    b.Navigation("PatientTurn");

                    b.Navigation("Psychologist");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("PD.Entity.Patient.Comment", b =>
                {
                    b.HasOne("PD.Entity.User.User", "User1")
                        .WithMany("Comments")
                        .HasForeignKey("FirstUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");
                });

            modelBuilder.Entity("PD.Entity.Patient.Patient", b =>
                {
                    b.HasOne("PD.Entity.User.User", "User")
                        .WithMany("Patient")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientExam", b =>
                {
                    b.HasOne("PD.Entity.Patient.Patient", "Patient")
                        .WithMany("PatientExam")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Test.Test", "Test")
                        .WithMany("PatientExam")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientFile", b =>
                {
                    b.HasOne("PD.Entity.Patient.Patient", "Patient")
                        .WithMany("PatientFile")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientResponses", b =>
                {
                    b.HasOne("PD.Entity.Patient.PatientExam", "PatientExam")
                        .WithMany("PatientResponses")
                        .HasForeignKey("PatientExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PatientExam");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientTurn", b =>
                {
                    b.HasOne("PD.Entity.Patient.Patient", "Patient")
                        .WithMany("PatientTurns")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Psychologist.PsychologistWorkingDateAndTime", "PsychologistWorkingDateAndTime")
                        .WithMany("PatientTurns")
                        .HasForeignKey("PsychologistWorkingDateAndTimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Psychologist.TypeOfConsultation", "TypeOfConsultation")
                        .WithMany("PatientTurns")
                        .HasForeignKey("TypeOfConsultationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("PsychologistWorkingDateAndTime");

                    b.Navigation("TypeOfConsultation");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.Psychologist", b =>
                {
                    b.HasOne("PD.Entity.User.User", "User")
                        .WithMany("Psychologists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistTypeOfConsultation", b =>
                {
                    b.HasOne("PD.Entity.Psychologist.Psychologist", "Psychologist")
                        .WithMany("PsychologistTypeOfConsultations")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Psychologist.TypeOfConsultation", "TypeOfConsultation")
                        .WithMany("PsychologistTypeOfConsultations")
                        .HasForeignKey("TypeOfConsultationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Psychologist");

                    b.Navigation("TypeOfConsultation");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistWorkingDateAndTime", b =>
                {
                    b.HasOne("PD.Entity.Psychologist.Psychologist", "Psychologist")
                        .WithMany("PsychologistWorkingDateAndTime")
                        .HasForeignKey("PsychologistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Psychologist.PsychologistWorkingDays", "PsychologistWorkingDays")
                        .WithMany("PsychologistWorkingDateAndTimes")
                        .HasForeignKey("PsychologistWorkingDaysId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Psychologist.PsychologistWorkingHours", "PsychologistWorkingHours")
                        .WithMany("PsychologistWorkingDateAndTimes")
                        .HasForeignKey("PsychologistWorkingHoursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Psychologist");

                    b.Navigation("PsychologistWorkingDays");

                    b.Navigation("PsychologistWorkingHours");
                });

            modelBuilder.Entity("PD.Entity.Test.Answer", b =>
                {
                    b.HasOne("PD.Entity.Test.Question", "Question")
                        .WithMany("Answer")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PD.Entity.Test.Question", b =>
                {
                    b.HasOne("PD.Entity.Test.Test", "Test")
                        .WithMany("Question")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("PD.Entity.User.User", b =>
                {
                    b.HasOne("PD.Entity.User.Gender", "Gender")
                        .WithMany("Users")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PD.Entity.Role.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PD.Entity.Patient.Patient", b =>
                {
                    b.Navigation("Discount");

                    b.Navigation("Orders");

                    b.Navigation("PatientExam");

                    b.Navigation("PatientFile");

                    b.Navigation("PatientTurns");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientExam", b =>
                {
                    b.Navigation("PatientResponses");
                });

            modelBuilder.Entity("PD.Entity.Patient.PatientTurn", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.Psychologist", b =>
                {
                    b.Navigation("Discount");

                    b.Navigation("Order");

                    b.Navigation("PsychologistTypeOfConsultations");

                    b.Navigation("PsychologistWorkingDateAndTime");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistWorkingDateAndTime", b =>
                {
                    b.Navigation("PatientTurns");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistWorkingDays", b =>
                {
                    b.Navigation("PsychologistWorkingDateAndTimes");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.PsychologistWorkingHours", b =>
                {
                    b.Navigation("PsychologistWorkingDateAndTimes");
                });

            modelBuilder.Entity("PD.Entity.Psychologist.TypeOfConsultation", b =>
                {
                    b.Navigation("PatientTurns");

                    b.Navigation("PsychologistTypeOfConsultations");
                });

            modelBuilder.Entity("PD.Entity.Role.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PD.Entity.Test.Question", b =>
                {
                    b.Navigation("Answer");
                });

            modelBuilder.Entity("PD.Entity.Test.Test", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("PatientExam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PD.Entity.User.Gender", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PD.Entity.User.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Patient");

                    b.Navigation("Psychologists");
                });
#pragma warning restore 612, 618
        }
    }
}
